name: montech
description: Akıllı mont projesi için Flutter frontend uygulaması.
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.0
  shared_preferences: ^2.2.2
  fl_chart: ^1.0.0
  url_launcher: ^6.2.5
  google_maps_flutter: ^2.12.3
  geolocator: ^14.0.1
  permission_handler: ^12.0.0+1
  flutter_blue_plus: ^1.35.5
  battery_plus: ^6.2.1
  flutter_lints: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700




